#!/bin/bash
# various sym links
echo Sym-linking
cd dist/frontend
ln -s ../../src/frontend/js .
ln -s ../../src/frontend/tutorials .
ln -s ../../src/frontend/default.m2 .
cd ../..
# katex fonts
cd public
ln -s ../KaTeX/submodules/katex-fonts/fonts .
cd ..
# VG
cd src/frontend/
echo Installing VectorGraphics
cd css
wget -nv -N https://raw.githubusercontent.com/pzinn/M2/vanilla/M2/Macaulay2/packages/VectorGraphics/VectorGraphics.css
cd ../js
wget -nv -N https://raw.githubusercontent.com/pzinn/M2/vanilla/M2/Macaulay2/packages/VectorGraphics/VectorGraphics.js
cd ..
# mdl
echo Installing Material Design Lite
cd js
wget -nv -N https://code.getmdl.io/1.3.0/material.js
cd ../css
wget -nv -N https://code.getmdl.io/1.3.0/material.indigo-deep_orange.min.css
cd ..
