#!/bin/bash
cd public
# KaTeX
echo Installing KaTeX
wget -nv https://github.com/pzinn/KaTeX/releases/download/v0.12.1-pzinn/dist.tar.gz
tar zxf dist.tar.gz
mv dist/*.css dist/fonts css
mv dist/*js js
rm -rf dist
rm dist.tar.gz
# VG
echo Installing VectorGraphics
cd css
wget -nv -N https://raw.githubusercontent.com/pzinn/M2/vanilla/M2/Macaulay2/packages/VectorGraphics/VectorGraphics.css
cd ../js
wget -nv -N https://raw.githubusercontent.com/pzinn/M2/vanilla/M2/Macaulay2/packages/VectorGraphics/VectorGraphics.js
cd ..
# mdl
echo Installing Material Design Lite
cd js
wget -nv -N https://code.getmdl.io/1.3.0/material.js
cd ../css
wget -nv -N https://code.getmdl.io/1.3.0/material.indigo-deep_orange.min.css
cd ..
