#!/bin/bash
# VG
cd src/frontend/
echo Installing VectorGraphics
mkdir -p css
cd css
wget -nv -N https://raw.githubusercontent.com/pzinn/M2/vanilla/M2/Macaulay2/packages/VectorGraphics/VectorGraphics.css
cd ..
mkdir -p js
cd js
wget -nv -N https://raw.githubusercontent.com/pzinn/M2/vanilla/M2/Macaulay2/packages/VectorGraphics/VectorGraphics.js
cd ..
# mdl
echo Installing Material Design Lite
cd js
wget -nv -N https://code.getmdl.io/1.3.0/material.js
cd ../css
wget -nv -N https://code.getmdl.io/1.3.0/material.indigo-deep_orange.min.css
cd ..
cd ../..
# various sym links
echo Sym-linking
cd dist/frontend
ln -sf ../../src/frontend/js .
ln -sf ../../src/frontend/tutorials .
ln -sf ../../src/frontend/default.m2 .
cd ../..
cd public
ln -sf ../src/frontend/js/VectorGraphics.js .
# katex fonts
ln -sf ../KaTeX/submodules/katex-fonts/fonts .
cd ..
